### PR TITLE
Circle-ci conversion

### PR DESCRIPTION
**Pull request by ahsojar**

### CODE REVIEW

**Comment by nathanleiby** [comment]
Looks like the tests expect for `REDIS_URL` to be set, but it's not present.

```
+ export REDIS_URL=:
+ REDIS_URL=:
```

**Comment by nathanleiby** [comment]
I think if you just remove this line, it should work

https://github.com/Clever/shorty/blob/master/integration_tests.sh#L4

These vars were set in drone but are no longer set in CircleCI.

Hopefully the default value of `REDIS_URL` will connect to redis running on localhost.

**Comment by ahsojar** [comment]
Thanks @nathanleiby ! it works now :)

**Comment by bstein-clever** [comment]
It's passing, so LGTM. :)

**Pull request merged**
